version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: kuckuc_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kuckuc_backend
    environment:
      GIN_MODE: release
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      UPLOAD_DIR: /app/uploads
      ENVIRONMENT: production
      ALLOWED_ORIGINS: https://kuckuc.rs,https://www.kuckuc.rs
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: kuckuc_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - uploads_data:/app/uploads:ro
    depends_on:
      - backend
    restart: always


volumes:
  postgres_data:
  uploads_data:
  frontend_build:
  nginx_conf:
